import {chainNames,gmgn,unwrap} from './_gmgn.js';
const usd=v=>{const n=Number(v||0);return n>=1e9?'$'+(n/1e9).toFixed(2)+'B':n>=1e6?'$'+(n/1e6).toFixed(1)+'M':n>=1e3?'$'+(n/1e3).toFixed(1)+'K':'$'+n.toFixed(2)};
const age=t=>{const h=Math.max(1,Math.floor((Date.now()-Number(t||0)*1000)/3600000));return t?(h<24?h+'h':Math.floor(h/24)+'d'):'—'};
const colors=['purple','yellow','pink','blue','orange','red'];
const canonical=value=>({sol:'sol',solana:'sol',bsc:'bsc',bnb:'bsc',base:'base',eth:'eth',ethereum:'eth',robinhood:'robinhood',rhc:'robinhood'})[String(value||'').toLowerCase()];
const dexChain={sol:'solana',bsc:'bsc',base:'base',eth:'ethereum',robinhood:'robinhood'};
let cached={expires:0,payload:null};
function token(x,fallbackChain,i){const chain=canonical(x.chain)||fallbackChain,vol=Number(x.volume||x.volume_24h||0),liq=Number(x.liquidity||0),cap=Number(x.market_cap||x.usd_market_cap||0),heat=Number(x.hot_level||0),change=Number(x.price_change_percent_24h??x.price_change_percent24h??x.price_change_percent??x.price_change_percent_1h??0),upside=change>0?Math.min(14,change*.08):0,downside=change<0?Math.min(42,Math.abs(change)*.45):0,score=Math.max(8,Math.min(99,Math.round(35+Math.min(22,Math.log10(vol+1)*3.5)+Math.min(15,Math.log10(liq+1)*2.8)+Math.min(9,heat*1.5)+upside-downside))),address=x.address||x.token_address||'';return{name:x.name||x.symbol||'Token',symbol:x.symbol||'TOKEN',chain:chainNames[chain]||chainNames[fallbackChain],address,logo:x.logo||x.logo_url||'',price:x.price?(Number(x.price)<.01?'$'+Number(x.price).toPrecision(3):'$'+Number(x.price).toFixed(4)):'—',change,cap:cap/1e6,vol:vol/1e6,liq:liq/1e6,age:age(x.open_timestamp||x.creation_timestamp||x.created_timestamp),score,signal:change<=-50?'Heavy selloff':change<=-15?'Weak momentum':heat?'Heat level '+heat:vol>liq?'High activity':'Trending',reason:change<=-50?'Large 24h drawdown is reducing this score.':'Live market-ranking data',color:colors[i%colors.length],url:address?'https://dexscreener.com/'+dexChain[chain]+'/'+address:'https://dexscreener.com'}}
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=90, stale-while-revalidate=240');if(cached.payload&&Date.now()<cached.expires)return res.status(200).json(cached.payload);try{const ids=['sol','bsc','base','eth','robinhood'];const [feeds,global,prices]=await Promise.all([Promise.all(ids.map(async chain=>({chain,data:await gmgn('/v1/market/rank',{chain,interval:'1h',limit:'18'}).catch(()=>null)}))),fetch('https://api.coingecko.com/api/v3/global',{signal:AbortSignal.timeout(6000)}).then(r=>r.ok?r.json():null).catch(()=>null),fetch('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,solana,binancecoin&vs_currencies=usd&include_24hr_change=true',{signal:AbortSignal.timeout(6000)}).then(r=>r.ok?r.json():null).catch(()=>null)]);const tokens=feeds.flatMap(({chain,data})=>{const payload=unwrap(data)||{},rows=payload.rank||payload.list||[];return rows.map((row,i)=>token(row,chain,i))}).filter(x=>x.vol>0&&x.liq>0).filter((x,i,all)=>all.findIndex(y=>y.chain===x.chain&&y.symbol===x.symbol)===i).sort((a,b)=>b.score-a.score).slice(0,50);if(!tokens.length)return res.status(502).json({error:'No live market data returned',tokens:[]});const d=global?.data,cap=Number(d?.total_market_cap?.usd||0),vol=Number(d?.total_volume?.usd||0),change=Number(d?.market_cap_change_percentage_24h_usd||0),trackedVol=tokens.reduce((n,x)=>n+x.vol,0)*1e6,quote=(id,symbol,label)=>({symbol,label,price:'$'+Number(prices?.[id]?.usd||0).toLocaleString(undefined,{maximumFractionDigits:2}),change:prices?.[id]?.usd_24h_change||0}),assets=[quote('bitcoin','BTC','Bitcoin'),quote('ethereum','ETH','Ethereum'),quote('solana','SOL','Solana'),quote('binancecoin','BNB','BNB Chain')],payload={tokens,market:{sentiment:change>3?'Greed':change<-3?'Fear':'Neutral',score:change>3?74:change<-3?32:51,marketCap:usd(cap),marketChange:change,volume:usd(vol),volumeChange:0,onChain:usd(trackedVol),assets,updated:'Live market feed'}};cached={payload,expires:Date.now()+90000};res.status(200).json(payload)}catch(e){res.status(502).json({error:e.message||'Market data unavailable',tokens:[]})}}
